
package sipembayaran.View;

import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author YAS
 */
public class FrmReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmReport
     */
    public FrmReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        splPenjualan = new javax.swing.JScrollPane();

        setClosable(true);

        jLabel2.setText("Month");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Mont --", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(189, Short.MAX_VALUE))
            .addComponent(splPenjualan)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(splPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntityManager em = null;
        try {
            em = sipembayaran.SIPembayaran.EMF.createEntityManager();
            em.getTransaction().begin();
            Connection connect = em.unwrap(Connection.class);
            File file = new File("");
            String sourcefilename = file.getAbsolutePath() + "\\src\\sipembayaran\\View\\Report\\ReportPenjualan.jasper";
            HashMap parameter = new HashMap();
            parameter.put("month", cmbMonth.getSelectedItem().toString());
            
            JasperPrint jp = JasperFillManager.fillReport(sourcefilename, parameter, connect);
//            //untuk buka report
//            JasperViewer jv = new JasperViewer(jp, false);
//            jv.setVisible(true);
//            //untuk buka report
            
            JRViewer viewer = new JRViewer(jp);
            viewer.setOpaque(true);
            viewer.setVisible(true);
            splPenjualan.add(viewer);
            splPenjualan.setViewportView(viewer);
            
            em.getTransaction().commit();
            connect.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tidak bisa Print:" + e.getMessage());

        } finally {
            if (em != null) {
                em.close();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane splPenjualan;
    // End of variables declaration//GEN-END:variables
}
